### ISSUE TITLE
Lib no longer maintained

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/tutorials#5]
This may be in the wrong section and is so my apologies.

Library referenced at this address is no longer available
`
https://github.com/nemith/serLCD
`
Requires update or removal.

**Comment by per1234** [comment]
This issue report is extremely vague but after some research I'm going to guess that you consider the disappearance of that library to be of interest to the Arduino developers because the Playground page:
https://playground.arduino.cc/Code/SerLCD
contained a link to that repository.

The Arduino Playground is a publicly editable wiki. The content of the Playground is the responsibility of the Arduino community, not of the Arduino developers. If you find a problem or room for improvement in the Playground feel free to edit it. If you would like to first discuss your proposed changes to the Playground please create a post on the [Website and Forum](http://forum.arduino.cc/index.php?board=24.0) section of the Arduino forum.

I removed the dead link from that Playground page. Luckily the source code of the library is included on that page so it has not been lost.

**Comment by facchinm** [comment]
Closing as solved
